# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT += core gui

TEMPLATE = app
TARGET = Clock

#DEFINES += QT_DLL

include(tao.pri)

win32:RC_FILE += res/version.rc

OTHER_FILES += \
    res/version.rc
